//Number guessing game
//User need to guess the number generated by the computer
//The System generates the number in a given range i.e., 1 to 100
//User enter the number and the system give them a small hint if they made a wrong guess
//Limited number of attempts, displays score, Giving points based on number of attempts

import java.util.Scanner;

public class GuessingGame
{
    public static void main(String[] args)
    {
        Scanner sc = new Scanner(System.in);
        System.out.println("\n--------------------\n| GUESS THE NUMBER | \n--------------------\n");
        System.out.println("Rules:");
        System.out.println("1.The number will be any integer in between 1 to 100. ");
        System.out.println("2.You will have 7 chances to guess the correct number.");
        System.out.println("3.Your accuracy percentage will be decreased for every wrong guess.\n");
        int score = 7, n;
        int r  = (int) (Math.random() * 101);
        while(score > 0)
        {
            System.out.println("\nWhat do you think the number is?");
            n = sc.nextInt();
            if(r == n)
            {
                if(score == 7)
                {
                 System.out.println("(\\_/) Perfect Guess!!!");
                 System.out.println("(^.^)");
                 System.out.println("(_^_)");
                }
                else
                 System.out.println("You won!");
                break;
            }
            else
            {
                if(score == 1)
                {
                 System.out.println("Better luck next time :(");
                 score--;
                 break;
                }
                if(n > r)
                 System.out.println("You are too far");
                else
                 System.out.println("Think big");
                System.out.println("Try again");
                score--;
                System.out.println("Chances left : " + score);
            }
        }
        System.out.println("The Correct Answer is " + r);
        System.out.println("Your Score = " + score*100 / 7 + "/100");
    }
}